get Error: 'First argument needs to be a number, array or string' with mime@1.2.10
buffer.js:238
        throw new Error('First argument needs to be a number, ' +
              ^
Error: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:238:15)
    at FormStream.field (./formstream/lib/formstream.js:135:16)
    at Service.uploadWithToken (./lib/rs.js:146:8)
    at Object.oncomplete (./lib/rs.js:183:10)